add arguments to main, 1st argument can be set as the input path.
TCThenna/GBLKinkEvaluator pull request #2
Opened 2017-03-07 13:32 UTC by dreyling

left default, if no argument (path) is given.

2017-03-07 13:43 UTC, TCThenna requested changes
Add also cmd line input for "runmode", which (if given) overwrites the runmode from the config file

2017-03-07 16:58 UTC, dreyling commented
Okay, now you should see the changes on run mode.. same request.

2017-03-08 08:02 UTC, TCThenna reviewed
I will add if() to only provide runmode but not input dir

2017-03-08 08:02 UTC, merged

2017-03-08 08:06 UTC, TCThenna commented on src/main.cc
> +  //std::string s_config = "../conf/config.txt";
instead of commenting out, next better just delete it. The old code is still git-ed, so we dont lose anything.